version: '3.7'
services:
  iris:
    init: true
    hostname: servertomonitor
    environment:
      #Do not use persistent sys: not needed for demo
      #- ISC_DATA_DIRECTORY=/dur/config
    ports:
      - '41773:51773'
      - '42773:52773'
    #image: store/intersystems/iris-community:2021.2.0.649.0
    #If your CPU has >8cores limit InterSystems IRIS CE rto 8 with
    cpuset: "0-7"
    build:
      context: .
      dockerfile: Dockerfile  
    restart:  on-failure
    volumes:
      - ./logs:/logs
    command: --check-caps false
networks:
    default:
      external:
        name: sam_default